name: Check
on: [push, pull_request]
jobs:
  lua-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.4
      - name: Check Lua syntax
        run: make check
      - name: Package game
        run: make build
